// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sai_Raj_Laboratory.Models;

namespace Sai_Raj_Laboratory.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220817182304_AddedBSAndCR1")]
    partial class AddedBSAndCR1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sai_Raj_Laboratory.Models.Report", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PateintEosinophils")
                        .HasColumnType("int");

                    b.Property<int>("PateintLymphocytes")
                        .HasColumnType("int");

                    b.Property<int>("PatientAge")
                        .HasColumnType("int");

                    b.Property<float?>("PatientBS")
                        .HasColumnType("real");

                    b.Property<int>("PatientBasophils")
                        .HasColumnType("int");

                    b.Property<float?>("PatientCreatinine")
                        .HasColumnType("real");

                    b.Property<float>("PatientHB")
                        .HasColumnType("real");

                    b.Property<int>("PatientMonocytes")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientNeutrophils")
                        .HasColumnType("int");

                    b.Property<string>("PatientParasitesStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPlateletesCount")
                        .HasColumnType("int");

                    b.Property<string>("PatientPlateletesStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientRBCStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PatientSex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientWBC")
                        .HasColumnType("int");

                    b.Property<string>("PatientWBCStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UHID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.ToTable("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
